### ISSUE TITLE
如何处理多标签分类，以及 label 字符数不固定 ？

### ISSUE THREAD

**Issue by liulu1998** [taishan1994/prompt_text_classification#1]
1. 如何处理 多标签分类（multi-label classification）？
2. 若 label 的字符数不固定为 2，如何处理 ？

**Comment by taishan1994** [comment]
> 1. 如何处理 多标签分类（multi-label classification）？
> 2. 若 label 的字符数不固定为 2，如何处理 ？

可参考这：https://www.zhihu.com/question/553062761
