### ISSUE TITLE
English Translation Please.

### ISSUE THREAD

**Issue by robinnarsinghranabhat** [taishan1994/prompt_text_classification#2]
This is the only repo I have come across that uses prompt based text classification. Google translate work's but an english version would make it lot accessible. Also, are there more resources like this repo ? I cannot find any. Internet full of repetitive fine-tuning articles using linear classifier. But not on this kind of approach.

**Comment by taishan1994** [comment]
> This is the only repo I have come across that uses prompt based text classification. Google translate work's but an english version would make it lot accessible. Also, are there more resources like this repo ? I cannot find any. Internet full of repetitive fine-tuning articles using linear classifier. But not on this kind of approach.

maybe this is helpful for you：

paper:：https://reader.elsevier.com/reader/sd/pii/S2666651022000183?token=B7153187146C22D5AA573D9E6E8C55AEE23FC89C11EF2B562E9839B776BCE379128B8D812A856201000AB8412B38D0CD&originRegion=us-east-1&originCreation=20230315103942
code：https://github.com/thunlp/PTR
