### ISSUE TITLE
求一个模型文件

### ISSUE THREAD

**Issue by xyxhchb** [taishan1994/prompt_text_classification#6]
你好，我这边网络原因下载不了模型，可以分享一下你的模型文件给我吗？

**Comment by taishan1994** [comment]
> 你好，我这边网络原因下载不了模型，可以分享一下你的模型文件给我吗？

我这边都没有保存额，自己训练一个挺快的。

**Comment by xyxhchb** [comment]
> > 你好，我这边网络原因下载不了模型，可以分享一下你的模型文件给我吗？
> 
> 我这边都没有保存额，自己训练一个挺快的。

已经解决了，挂梯子下载了一个，感谢回复
